#!/bin/bash

# specify only exp-specific parameters
src=c11node9
dest=c11node10
router=c11node28

ganglia=10.244.36.20

# RTT = delay*2
rtt=180	# 180ms RTT
#rtt=80	# 80ms RTT
#rtt=20	# 20ms RTT
#rtt=0		# 0.4ms RTT (LAN)
delay=$(( rtt / 2 ))
#rtt=$(( delay * 2 ))ms

vwnd=8
run=1
prefix=${vwnd}vms-r${run}
#prefix=1vm-r4

# ping or pong
turn=pong

logdir=/root/qm/log
logfile=$logdir/${prefix}.logfile

# last minutes for ganglia metrics
#min=3min
min=5min

# download ganglia metrics
function download() {
        wget -O $prefix.src.net.png "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=c11node9&s=by+name&g=network_report"
        wget -O $prefix.src.net.csv "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=c11node9&s=by+name&g=network_report&csv=1"
        wget -O $prefix.src.cpu.png "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=c11node9&s=by+name&g=cpu_report"
        wget -O $prefix.src.cpu.csv "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=c11node9&s=by+name&g=cpu_report&csv=1"
        wget -O $prefix.dest.net.png "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=${dest}&s=by+name&g=network_report"
        wget -O $prefix.dest.net.csv "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=${dest}&s=by+name&g=network_report&csv=1"
        wget -O $prefix.dest.cpu.png "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=${dest}&s=by+name&g=cpu_report"
        wget -O $prefix.dest.cpu.csv "http://10.244.36.20/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=${dest}&s=by+name&g=cpu_report&csv=1"

	for node in master slave1 slave2 slave3
	do
		for resource in cpu network
		do
			#for filetype in png csv
			#do
	        		wget -O $prefix.$node.$resource.png "http://${ganglia}/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=${node}&s=by+name&g=${resource}_report"
	        		wget -O $prefix.$node.$resource.csv "http://${ganglia}/ganglia/graph.php?r=${min}&z=medium&c=Hadoop&h=${node}&s=by+name&g=${resource}_report&csv=1"
			#done
		done
	done
}

ssh $router service tc delay $delay

# run workload: wordcount, terasort, kmeans, fuzzy kmeans, LDA
#ssh master "cd /root/mahout; ./run" &

if [ $rtt == 0 ]; then
	rtt=0.4
fi

#logsave $logfile time -p ./migrate $vwnd $run $rtt $turn
time -p ./qmigrate $vwnd $run ${rtt}ms $turn

# [ping] c11node9 to c11node10
#if [[ $turn == "ping" ]]; then
#	./migrate $vwnd $run $rtt
#fi

# [pong] c11node10 to c11node9
#if [[ $turn == "pong" ]]; then
#	./migrate $vwnd $run $rtt
#	ssh $dest "cd /root/qemu/; ./cluster $vwnd $run"
#fi

#download

ssh $router service tc stop
