#!/bin/bash

hosts=( c11node9 c11node10 )

#DEBUG=true
DEBUG=false

#cmd="ps -ef | grep qemu | awk '{print \$10,\$14,\$15,\$16,\$17,\$19,\$20,\$21,\$23}' | egrep 'slave|master|tomcat|jboss|mysql'"

# command to execute for each VM
# memory used
cmd="free -m | head -2 | tail -1"

# get VM names
vmnamecmd="ps -ef | grep qemu | grep -v grep | awk '{print \$10}'"

echo -e "Node \t                 total       used       free     shared    buffers     cached"

# for each host, first get the list of VM names
# and execute the command (cmd) for each VM via ssh
for host in ${hosts[@]}
do
	# get the list of the VM names 
	vmstr=`ssh $host $vmnamecmd`
	#echo $vmstr
	vms=($vmstr)	

#	echo ${vms[*]}

	# display host with the number of VMs running on it
	echo -n "$host (${#vms[@]}vms) "
	ssh $host "$cmd"

	# execute the command (cmd) for each VM via ssh
	i=1
	for vm in ${vms[@]}
	do
		# file=/var/lib/libvirt/images/nfs/c11node9/slave6.qcow2
                if [[ $vm == *qcow2* ]]; then
                        #echo qcow2
                        vm=${vm%.qcow2}
                        #echo $vm
                        vm=${vm##*/}
                        #echo $vm
                fi

		echo -n "vm$i: $vm "
		if ! $DEBUG; then
			ssh $vm $cmd
		fi

		i=$(( i + 1 ))
	done

	# grep name or image name
	vmnames=`ssh $host ps -ef | grep qemu`
	#echo "$qlist"
	#ssh c11node10 $cmd
	echo
done

