#!/bin/bash

# stop VM by name
#host=c11node9
host=$1
#host=localhost

#name=hadoop
name=$2

#port=4446
#port=

port=`ssh $host ps -ef | grep qemu | grep $name | awk '{print $19}'`
IFS='=:, '
read -a array <<< "$port"
IFS=''

#echo ${array[2]}
port=${array[2]}

function stopVM () {
nc $host $port << EOF
info status
quit
EOF
echo
}

echo stoppng VM $name on $host:$port ...
stopVM
echo done

#info version
